# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge
neo_version=21.1.226
loader_version_range=[1,)

# Mod properties
mod_id=thinlogs
mod_name=Artemis' Thin Logs
mod_license=MIT License
mod_version=0.2r
mod_group_id=de.artemis.thinlogs
mod_authors=Doomed_Artemis
mod_description=This mod adds thinner logs for all wood types. Leaves, snow, and carpets can be placed around the log.
