modLoader = "javafml"
loaderVersion = "[47,)"
license = "Apache 2.0"
[[mods]]
modId = "thinlogs"
version = "${file.jarVersion}"
displayName = "Artemis' ThinLogs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/artemis-thin-logs"
logoFile="artemis_thin_logs-logo.png"
logoBlur = true
authors="Artemis"
description = '''
This mod adds thinner logs for all wood types. Leaves, snow and carpets can be placed around the log.
'''

[[dependencies.thinlogs]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.thinlogs]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"
